language: ruby
sudo:     false
cache:    bundler
script:   bundle exec rspec
env:
  - CODECLIMATE_REPO_TOKEN=8e9b89269d9aafc2dec2706a43825201de496b743505d7a7666068f7b22b07d
rvm:
  - '1.9.3'
  - '2.0'
  - '2.1'
  - '2.2'
  - '2.3.0'
  - rbx-2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
